package monitor

import (
	"math"
	"strings"
	"sync"
	"time"
	"unicode"
)

// DNSAlert represents a suspicious DNS activity detection.
type DNSAlert struct {
	AlertType   string    `json:"alert_type"` // tunneling, dga, high_entropy, unusual_tld
	Domain      string    `json:"domain"`
	QueryType   string    `json:"query_type"` // A, AAAA, TXT, CNAME, MX
	Entropy     float64   `json:"entropy"`
	Score       float64   `json:"score"`
	Severity    string    `json:"severity"`
	Description string    `json:"description"`
	Timestamp   time.Time `json:"timestamp"`
}

// DNSMonitor analyzes DNS queries for tunneling, DGA domains, and anomalies.
type DNSMonitor struct {
	mu     sync.RWMutex
	alerts chan DNSAlert

	// Query counters per source (for rate anomaly detection)
	queryCounts map[string]*dnsSourceStats // source IP -> stats

	// Known-good domains to exclude from analysis
	allowlist map[string]bool
}

type dnsSourceStats struct {
	totalQueries   int
	txtQueries     int
	uniqueDomains  map[string]bool
	highEntropyHit int
	windowStart    time.Time
}

func NewDNSMonitor() *DNSMonitor {
	return &DNSMonitor{
		alerts:      make(chan DNSAlert, 512),
		queryCounts: make(map[string]*dnsSourceStats),
		allowlist: map[string]bool{
			"google.com": true, "googleapis.com": true, "gstatic.com": true,
			"amazonaws.com": true, "cloudfront.net": true,
			"github.com": true, "githubcopilot.com": true,
			"docker.io": true, "docker.com": true,
			"kubernetes.io": true, "k8s.io": true,
			"sentiae.com": true,
		},
	}
}

// Alerts returns the channel of DNS alerts.
func (m *DNSMonitor) Alerts() <-chan DNSAlert {
	return m.alerts
}

// AnalyzeQuery processes a DNS query and checks for suspicious patterns.
func (m *DNSMonitor) AnalyzeQuery(sourceIP, domain, queryType string) {
	// Skip allowed domains
	baseDomain := extractBaseDomain(domain)
	if m.allowlist[baseDomain] {
		return
	}

	now := time.Now()

	// Update source stats
	m.mu.Lock()
	stats, ok := m.queryCounts[sourceIP]
	if !ok || now.Sub(stats.windowStart) > 5*time.Minute {
		stats = &dnsSourceStats{
			uniqueDomains: make(map[string]bool),
			windowStart:   now,
		}
		m.queryCounts[sourceIP] = stats
	}
	stats.totalQueries++
	stats.uniqueDomains[domain] = true
	if queryType == "TXT" {
		stats.txtQueries++
	}
	m.mu.Unlock()

	// Check 1: DNS tunneling indicators
	if m.isTunnelingIndicator(domain, queryType, stats) {
		m.emitAlert(DNSAlert{
			AlertType:   "tunneling",
			Domain:      domain,
			QueryType:   queryType,
			Severity:    "high",
			Description: "Suspected DNS tunneling: high-entropy subdomain with TXT queries from " + sourceIP,
			Timestamp:   now,
		})
	}

	// Check 2: DGA (Domain Generation Algorithm) pattern
	if dgaScore := m.dgaScore(domain); dgaScore > 0.7 {
		m.emitAlert(DNSAlert{
			AlertType:   "dga",
			Domain:      domain,
			QueryType:   queryType,
			Score:       dgaScore,
			Severity:    "high",
			Description: "Possible DGA domain detected",
			Timestamp:   now,
		})
	}

	// Check 3: High-entropy subdomain (data exfiltration indicator)
	entropy := m.subdomainEntropy(domain)
	if entropy > 4.0 && len(domain) > 40 {
		m.emitAlert(DNSAlert{
			AlertType:   "high_entropy",
			Domain:      domain,
			QueryType:   queryType,
			Entropy:     entropy,
			Severity:    "medium",
			Description: "High-entropy DNS query (possible data exfiltration)",
			Timestamp:   now,
		})
	}
}

// isTunnelingIndicator detects DNS tunneling patterns.
func (m *DNSMonitor) isTunnelingIndicator(domain, queryType string, stats *dnsSourceStats) bool {
	// High rate of TXT queries to same base domain is a strong tunneling indicator
	if queryType == "TXT" && stats.txtQueries > 10 {
		return true
	}

	// Very long subdomains (encoded data)
	parts := strings.Split(domain, ".")
	for _, part := range parts {
		if len(part) > 50 {
			return true
		}
	}

	// High unique domain count in short time (fast-flux/tunneling)
	if len(stats.uniqueDomains) > 100 {
		return true
	}

	return false
}

// dgaScore computes a probability (0-1) that a domain was generated by a DGA.
// Uses character frequency analysis, consonant-to-vowel ratio, and bigram analysis.
func (m *DNSMonitor) dgaScore(domain string) float64 {
	baseDomain := extractBaseDomain(domain)
	name := strings.Split(baseDomain, ".")[0] // Just the domain name without TLD

	if len(name) < 6 {
		return 0 // Short domains are unlikely DGA
	}

	score := 0.0
	factors := 0.0

	// Factor 1: Entropy of the domain name
	entropy := shannonEntropy(name)
	if entropy > 3.5 {
		score += 0.3
	}
	factors += 0.3

	// Factor 2: Consonant-to-vowel ratio (DGA domains tend to have unusual ratios)
	vowels, consonants := 0, 0
	for _, c := range strings.ToLower(name) {
		if strings.ContainsRune("aeiou", c) {
			vowels++
		} else if unicode.IsLetter(c) {
			consonants++
		}
	}
	if vowels > 0 {
		ratio := float64(consonants) / float64(vowels)
		if ratio > 4.0 || ratio < 0.5 { // Normal English is ~1.5-2.5
			score += 0.25
		}
	} else {
		score += 0.25 // No vowels at all is very suspicious
	}
	factors += 0.25

	// Factor 3: Digit density (DGA domains often have many digits)
	digits := 0
	for _, c := range name {
		if unicode.IsDigit(c) {
			digits++
		}
	}
	digitRatio := float64(digits) / float64(len(name))
	if digitRatio > 0.3 {
		score += 0.25
	}
	factors += 0.25

	// Factor 4: Length (DGA domains tend to be 10-20+ chars)
	if len(name) > 12 {
		score += 0.2
	}
	factors += 0.2

	return score / factors
}

// subdomainEntropy calculates Shannon entropy of the subdomain portion.
func (m *DNSMonitor) subdomainEntropy(domain string) float64 {
	parts := strings.Split(domain, ".")
	if len(parts) <= 2 {
		return 0 // No subdomain
	}
	// Everything except the last two parts (domain.tld) is the subdomain
	subdomain := strings.Join(parts[:len(parts)-2], ".")
	return shannonEntropy(subdomain)
}

// shannonEntropy computes the Shannon entropy of a string (bits per character).
func shannonEntropy(s string) float64 {
	if len(s) == 0 {
		return 0
	}

	freq := make(map[rune]int)
	for _, c := range s {
		freq[c]++
	}

	entropy := 0.0
	n := float64(len(s))
	for _, count := range freq {
		p := float64(count) / n
		if p > 0 {
			entropy -= p * math.Log2(p)
		}
	}

	return entropy
}

func (m *DNSMonitor) emitAlert(alert DNSAlert) {
	select {
	case m.alerts <- alert:
	default:
	}
}

// extractBaseDomain extracts the registerable domain from a full domain name.
func extractBaseDomain(domain string) string {
	domain = strings.TrimSuffix(domain, ".")
	parts := strings.Split(domain, ".")
	if len(parts) <= 2 {
		return domain
	}
	return strings.Join(parts[len(parts)-2:], ".")
}
