// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/sentiae/vigil/service/internal/port/repository"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function with given fields: ctx, event
func (_m *MockOutboxRepository) Insert(ctx context.Context, event *repository.OutboxEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.OutboxEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockOutboxRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - event *repository.OutboxEvent
func (_e *MockOutboxRepository_Expecter) Insert(ctx interface{}, event interface{}) *MockOutboxRepository_Insert_Call {
	return &MockOutboxRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, event)}
}

func (_c *MockOutboxRepository_Insert_Call) Run(run func(ctx context.Context, event *repository.OutboxEvent)) *MockOutboxRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repository.OutboxEvent))
	})
	return _c
}

func (_c *MockOutboxRepository_Insert_Call) Return(_a0 error) *MockOutboxRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_Insert_Call) RunAndReturn(run func(context.Context, *repository.OutboxEvent) error) *MockOutboxRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// ListUndelivered provides a mock function with given fields: ctx, limit
func (_m *MockOutboxRepository) ListUndelivered(ctx context.Context, limit int) ([]*repository.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListUndelivered")
	}

	var r0 []*repository.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*repository.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*repository.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepository_ListUndelivered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUndelivered'
type MockOutboxRepository_ListUndelivered_Call struct {
	*mock.Call
}

// ListUndelivered is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOutboxRepository_Expecter) ListUndelivered(ctx interface{}, limit interface{}) *MockOutboxRepository_ListUndelivered_Call {
	return &MockOutboxRepository_ListUndelivered_Call{Call: _e.mock.On("ListUndelivered", ctx, limit)}
}

func (_c *MockOutboxRepository_ListUndelivered_Call) Run(run func(ctx context.Context, limit int)) *MockOutboxRepository_ListUndelivered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOutboxRepository_ListUndelivered_Call) Return(_a0 []*repository.OutboxEvent, _a1 error) *MockOutboxRepository_ListUndelivered_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepository_ListUndelivered_Call) RunAndReturn(run func(context.Context, int) ([]*repository.OutboxEvent, error)) *MockOutboxRepository_ListUndelivered_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDelivered provides a mock function with given fields: ctx, id
func (_m *MockOutboxRepository) MarkDelivered(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkDelivered")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_MarkDelivered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDelivered'
type MockOutboxRepository_MarkDelivered_Call struct {
	*mock.Call
}

// MarkDelivered is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOutboxRepository_Expecter) MarkDelivered(ctx interface{}, id interface{}) *MockOutboxRepository_MarkDelivered_Call {
	return &MockOutboxRepository_MarkDelivered_Call{Call: _e.mock.On("MarkDelivered", ctx, id)}
}

func (_c *MockOutboxRepository_MarkDelivered_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOutboxRepository_MarkDelivered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOutboxRepository_MarkDelivered_Call) Return(_a0 error) *MockOutboxRepository_MarkDelivered_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_MarkDelivered_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockOutboxRepository_MarkDelivered_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
