// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/sentiae/vigil/service/internal/port/repository"

	time "time"

	uuid "github.com/google/uuid"
)

// MockAnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type MockAnalyticsRepository struct {
	mock.Mock
}

type MockAnalyticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepository_Expecter {
	return &MockAnalyticsRepository_Expecter{mock: &_m.Mock}
}

// FindingTrends provides a mock function with given fields: ctx, tenantID, from, to
func (_m *MockAnalyticsRepository) FindingTrends(ctx context.Context, tenantID uuid.UUID, from time.Time, to time.Time) ([]repository.FindingTrend, error) {
	ret := _m.Called(ctx, tenantID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindingTrends")
	}

	var r0 []repository.FindingTrend
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]repository.FindingTrend, error)); ok {
		return rf(ctx, tenantID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []repository.FindingTrend); ok {
		r0 = rf(ctx, tenantID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.FindingTrend)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, tenantID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnalyticsRepository_FindingTrends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindingTrends'
type MockAnalyticsRepository_FindingTrends_Call struct {
	*mock.Call
}

// FindingTrends is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockAnalyticsRepository_Expecter) FindingTrends(ctx interface{}, tenantID interface{}, from interface{}, to interface{}) *MockAnalyticsRepository_FindingTrends_Call {
	return &MockAnalyticsRepository_FindingTrends_Call{Call: _e.mock.On("FindingTrends", ctx, tenantID, from, to)}
}

func (_c *MockAnalyticsRepository_FindingTrends_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, from time.Time, to time.Time)) *MockAnalyticsRepository_FindingTrends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockAnalyticsRepository_FindingTrends_Call) Return(_a0 []repository.FindingTrend, _a1 error) *MockAnalyticsRepository_FindingTrends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnalyticsRepository_FindingTrends_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]repository.FindingTrend, error)) *MockAnalyticsRepository_FindingTrends_Call {
	_c.Call.Return(run)
	return _c
}

// InsertFinding provides a mock function with given fields: ctx, finding
func (_m *MockAnalyticsRepository) InsertFinding(ctx context.Context, finding *domain.Finding) error {
	ret := _m.Called(ctx, finding)

	if len(ret) == 0 {
		panic("no return value specified for InsertFinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Finding) error); ok {
		r0 = rf(ctx, finding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnalyticsRepository_InsertFinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFinding'
type MockAnalyticsRepository_InsertFinding_Call struct {
	*mock.Call
}

// InsertFinding is a helper method to define mock.On call
//   - ctx context.Context
//   - finding *domain.Finding
func (_e *MockAnalyticsRepository_Expecter) InsertFinding(ctx interface{}, finding interface{}) *MockAnalyticsRepository_InsertFinding_Call {
	return &MockAnalyticsRepository_InsertFinding_Call{Call: _e.mock.On("InsertFinding", ctx, finding)}
}

func (_c *MockAnalyticsRepository_InsertFinding_Call) Run(run func(ctx context.Context, finding *domain.Finding)) *MockAnalyticsRepository_InsertFinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Finding))
	})
	return _c
}

func (_c *MockAnalyticsRepository_InsertFinding_Call) Return(_a0 error) *MockAnalyticsRepository_InsertFinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnalyticsRepository_InsertFinding_Call) RunAndReturn(run func(context.Context, *domain.Finding) error) *MockAnalyticsRepository_InsertFinding_Call {
	_c.Call.Return(run)
	return _c
}

// InsertFindings provides a mock function with given fields: ctx, findings
func (_m *MockAnalyticsRepository) InsertFindings(ctx context.Context, findings []*domain.Finding) error {
	ret := _m.Called(ctx, findings)

	if len(ret) == 0 {
		panic("no return value specified for InsertFindings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Finding) error); ok {
		r0 = rf(ctx, findings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAnalyticsRepository_InsertFindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFindings'
type MockAnalyticsRepository_InsertFindings_Call struct {
	*mock.Call
}

// InsertFindings is a helper method to define mock.On call
//   - ctx context.Context
//   - findings []*domain.Finding
func (_e *MockAnalyticsRepository_Expecter) InsertFindings(ctx interface{}, findings interface{}) *MockAnalyticsRepository_InsertFindings_Call {
	return &MockAnalyticsRepository_InsertFindings_Call{Call: _e.mock.On("InsertFindings", ctx, findings)}
}

func (_c *MockAnalyticsRepository_InsertFindings_Call) Run(run func(ctx context.Context, findings []*domain.Finding)) *MockAnalyticsRepository_InsertFindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.Finding))
	})
	return _c
}

func (_c *MockAnalyticsRepository_InsertFindings_Call) Return(_a0 error) *MockAnalyticsRepository_InsertFindings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnalyticsRepository_InsertFindings_Call) RunAndReturn(run func(context.Context, []*domain.Finding) error) *MockAnalyticsRepository_InsertFindings_Call {
	_c.Call.Return(run)
	return _c
}

// ScanMetrics provides a mock function with given fields: ctx, tenantID, from, to
func (_m *MockAnalyticsRepository) ScanMetrics(ctx context.Context, tenantID uuid.UUID, from time.Time, to time.Time) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, tenantID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ScanMetrics")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]map[string]interface{}, error)); ok {
		return rf(ctx, tenantID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []map[string]interface{}); ok {
		r0 = rf(ctx, tenantID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, tenantID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnalyticsRepository_ScanMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanMetrics'
type MockAnalyticsRepository_ScanMetrics_Call struct {
	*mock.Call
}

// ScanMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockAnalyticsRepository_Expecter) ScanMetrics(ctx interface{}, tenantID interface{}, from interface{}, to interface{}) *MockAnalyticsRepository_ScanMetrics_Call {
	return &MockAnalyticsRepository_ScanMetrics_Call{Call: _e.mock.On("ScanMetrics", ctx, tenantID, from, to)}
}

func (_c *MockAnalyticsRepository_ScanMetrics_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, from time.Time, to time.Time)) *MockAnalyticsRepository_ScanMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockAnalyticsRepository_ScanMetrics_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockAnalyticsRepository_ScanMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnalyticsRepository_ScanMetrics_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]map[string]interface{}, error)) *MockAnalyticsRepository_ScanMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// SearchFindings provides a mock function with given fields: ctx, tenantID, query, limit
func (_m *MockAnalyticsRepository) SearchFindings(ctx context.Context, tenantID uuid.UUID, query string, limit int) ([]*domain.Finding, error) {
	ret := _m.Called(ctx, tenantID, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchFindings")
	}

	var r0 []*domain.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) ([]*domain.Finding, error)); ok {
		return rf(ctx, tenantID, query, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) []*domain.Finding); ok {
		r0 = rf(ctx, tenantID, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = rf(ctx, tenantID, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnalyticsRepository_SearchFindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchFindings'
type MockAnalyticsRepository_SearchFindings_Call struct {
	*mock.Call
}

// SearchFindings is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - query string
//   - limit int
func (_e *MockAnalyticsRepository_Expecter) SearchFindings(ctx interface{}, tenantID interface{}, query interface{}, limit interface{}) *MockAnalyticsRepository_SearchFindings_Call {
	return &MockAnalyticsRepository_SearchFindings_Call{Call: _e.mock.On("SearchFindings", ctx, tenantID, query, limit)}
}

func (_c *MockAnalyticsRepository_SearchFindings_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, query string, limit int)) *MockAnalyticsRepository_SearchFindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockAnalyticsRepository_SearchFindings_Call) Return(_a0 []*domain.Finding, _a1 error) *MockAnalyticsRepository_SearchFindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnalyticsRepository_SearchFindings_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, int) ([]*domain.Finding, error)) *MockAnalyticsRepository_SearchFindings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnalyticsRepository creates a new instance of MockAnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
