// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/sentiae/platform-kit/kafka"
	mock "github.com/stretchr/testify/mock"
)

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockPublisher) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPublisher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPublisher_Expecter) Close() *MockPublisher_Close_Call {
	return &MockPublisher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPublisher_Close_Call) Run(run func()) *MockPublisher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPublisher_Close_Call) Return(_a0 error) *MockPublisher_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_Close_Call) RunAndReturn(run func() error) *MockPublisher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, eventType, data
func (_m *MockPublisher) Publish(ctx context.Context, eventType string, data kafka.EventData) error {
	ret := _m.Called(ctx, eventType, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, kafka.EventData) error); ok {
		r0 = rf(ctx, eventType, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
//   - data kafka.EventData
func (_e *MockPublisher_Expecter) Publish(ctx interface{}, eventType interface{}, data interface{}) *MockPublisher_Publish_Call {
	return &MockPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, eventType, data)}
}

func (_c *MockPublisher_Publish_Call) Run(run func(ctx context.Context, eventType string, data kafka.EventData)) *MockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(kafka.EventData))
	})
	return _c
}

func (_c *MockPublisher_Publish_Call) Return(_a0 error) *MockPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_Publish_Call) RunAndReturn(run func(context.Context, string, kafka.EventData) error) *MockPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// PublishBatch provides a mock function with given fields: ctx, events
func (_m *MockPublisher) PublishBatch(ctx context.Context, events []kafka.Event) error {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for PublishBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []kafka.Event) error); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishBatch'
type MockPublisher_PublishBatch_Call struct {
	*mock.Call
}

// PublishBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - events []kafka.Event
func (_e *MockPublisher_Expecter) PublishBatch(ctx interface{}, events interface{}) *MockPublisher_PublishBatch_Call {
	return &MockPublisher_PublishBatch_Call{Call: _e.mock.On("PublishBatch", ctx, events)}
}

func (_c *MockPublisher_PublishBatch_Call) Run(run func(ctx context.Context, events []kafka.Event)) *MockPublisher_PublishBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]kafka.Event))
	})
	return _c
}

func (_c *MockPublisher_PublishBatch_Call) Return(_a0 error) *MockPublisher_PublishBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishBatch_Call) RunAndReturn(run func(context.Context, []kafka.Event) error) *MockPublisher_PublishBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
