// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGatePolicyRepository is an autogenerated mock type for the GatePolicyRepository type
type MockGatePolicyRepository struct {
	mock.Mock
}

type MockGatePolicyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGatePolicyRepository) EXPECT() *MockGatePolicyRepository_Expecter {
	return &MockGatePolicyRepository_Expecter{mock: &_m.Mock}
}

// DeletePolicy provides a mock function with given fields: ctx, tenantID
func (_m *MockGatePolicyRepository) DeletePolicy(ctx context.Context, tenantID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGatePolicyRepository_DeletePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePolicy'
type MockGatePolicyRepository_DeletePolicy_Call struct {
	*mock.Call
}

// DeletePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockGatePolicyRepository_Expecter) DeletePolicy(ctx interface{}, tenantID interface{}) *MockGatePolicyRepository_DeletePolicy_Call {
	return &MockGatePolicyRepository_DeletePolicy_Call{Call: _e.mock.On("DeletePolicy", ctx, tenantID)}
}

func (_c *MockGatePolicyRepository_DeletePolicy_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockGatePolicyRepository_DeletePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGatePolicyRepository_DeletePolicy_Call) Return(_a0 error) *MockGatePolicyRepository_DeletePolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGatePolicyRepository_DeletePolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGatePolicyRepository_DeletePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserPref provides a mock function with given fields: ctx, tenantID, userID
func (_m *MockGatePolicyRepository) DeleteUserPref(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPref")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGatePolicyRepository_DeleteUserPref_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPref'
type MockGatePolicyRepository_DeleteUserPref_Call struct {
	*mock.Call
}

// DeleteUserPref is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGatePolicyRepository_Expecter) DeleteUserPref(ctx interface{}, tenantID interface{}, userID interface{}) *MockGatePolicyRepository_DeleteUserPref_Call {
	return &MockGatePolicyRepository_DeleteUserPref_Call{Call: _e.mock.On("DeleteUserPref", ctx, tenantID, userID)}
}

func (_c *MockGatePolicyRepository_DeleteUserPref_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID)) *MockGatePolicyRepository_DeleteUserPref_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGatePolicyRepository_DeleteUserPref_Call) Return(_a0 error) *MockGatePolicyRepository_DeleteUserPref_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGatePolicyRepository_DeleteUserPref_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockGatePolicyRepository_DeleteUserPref_Call {
	_c.Call.Return(run)
	return _c
}

// FindPolicy provides a mock function with given fields: ctx, tenantID
func (_m *MockGatePolicyRepository) FindPolicy(ctx context.Context, tenantID uuid.UUID) (*domain.GatePolicy, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindPolicy")
	}

	var r0 *domain.GatePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.GatePolicy, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.GatePolicy); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GatePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGatePolicyRepository_FindPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPolicy'
type MockGatePolicyRepository_FindPolicy_Call struct {
	*mock.Call
}

// FindPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockGatePolicyRepository_Expecter) FindPolicy(ctx interface{}, tenantID interface{}) *MockGatePolicyRepository_FindPolicy_Call {
	return &MockGatePolicyRepository_FindPolicy_Call{Call: _e.mock.On("FindPolicy", ctx, tenantID)}
}

func (_c *MockGatePolicyRepository_FindPolicy_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockGatePolicyRepository_FindPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGatePolicyRepository_FindPolicy_Call) Return(_a0 *domain.GatePolicy, _a1 error) *MockGatePolicyRepository_FindPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGatePolicyRepository_FindPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.GatePolicy, error)) *MockGatePolicyRepository_FindPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserPref provides a mock function with given fields: ctx, tenantID, userID
func (_m *MockGatePolicyRepository) FindUserPref(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID) (*domain.GateUserPref, error) {
	ret := _m.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserPref")
	}

	var r0 *domain.GateUserPref
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.GateUserPref, error)); ok {
		return rf(ctx, tenantID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.GateUserPref); ok {
		r0 = rf(ctx, tenantID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GateUserPref)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGatePolicyRepository_FindUserPref_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserPref'
type MockGatePolicyRepository_FindUserPref_Call struct {
	*mock.Call
}

// FindUserPref is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGatePolicyRepository_Expecter) FindUserPref(ctx interface{}, tenantID interface{}, userID interface{}) *MockGatePolicyRepository_FindUserPref_Call {
	return &MockGatePolicyRepository_FindUserPref_Call{Call: _e.mock.On("FindUserPref", ctx, tenantID, userID)}
}

func (_c *MockGatePolicyRepository_FindUserPref_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, userID uuid.UUID)) *MockGatePolicyRepository_FindUserPref_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGatePolicyRepository_FindUserPref_Call) Return(_a0 *domain.GateUserPref, _a1 error) *MockGatePolicyRepository_FindUserPref_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGatePolicyRepository_FindUserPref_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.GateUserPref, error)) *MockGatePolicyRepository_FindUserPref_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPolicy provides a mock function with given fields: ctx, p
func (_m *MockGatePolicyRepository) UpsertPolicy(ctx context.Context, p *domain.GatePolicy) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GatePolicy) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGatePolicyRepository_UpsertPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPolicy'
type MockGatePolicyRepository_UpsertPolicy_Call struct {
	*mock.Call
}

// UpsertPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.GatePolicy
func (_e *MockGatePolicyRepository_Expecter) UpsertPolicy(ctx interface{}, p interface{}) *MockGatePolicyRepository_UpsertPolicy_Call {
	return &MockGatePolicyRepository_UpsertPolicy_Call{Call: _e.mock.On("UpsertPolicy", ctx, p)}
}

func (_c *MockGatePolicyRepository_UpsertPolicy_Call) Run(run func(ctx context.Context, p *domain.GatePolicy)) *MockGatePolicyRepository_UpsertPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.GatePolicy))
	})
	return _c
}

func (_c *MockGatePolicyRepository_UpsertPolicy_Call) Return(_a0 error) *MockGatePolicyRepository_UpsertPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGatePolicyRepository_UpsertPolicy_Call) RunAndReturn(run func(context.Context, *domain.GatePolicy) error) *MockGatePolicyRepository_UpsertPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserPref provides a mock function with given fields: ctx, p
func (_m *MockGatePolicyRepository) UpsertUserPref(ctx context.Context, p *domain.GateUserPref) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserPref")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GateUserPref) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGatePolicyRepository_UpsertUserPref_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserPref'
type MockGatePolicyRepository_UpsertUserPref_Call struct {
	*mock.Call
}

// UpsertUserPref is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.GateUserPref
func (_e *MockGatePolicyRepository_Expecter) UpsertUserPref(ctx interface{}, p interface{}) *MockGatePolicyRepository_UpsertUserPref_Call {
	return &MockGatePolicyRepository_UpsertUserPref_Call{Call: _e.mock.On("UpsertUserPref", ctx, p)}
}

func (_c *MockGatePolicyRepository_UpsertUserPref_Call) Run(run func(ctx context.Context, p *domain.GateUserPref)) *MockGatePolicyRepository_UpsertUserPref_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.GateUserPref))
	})
	return _c
}

func (_c *MockGatePolicyRepository_UpsertUserPref_Call) Return(_a0 error) *MockGatePolicyRepository_UpsertUserPref_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGatePolicyRepository_UpsertUserPref_Call) RunAndReturn(run func(context.Context, *domain.GateUserPref) error) *MockGatePolicyRepository_UpsertUserPref_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGatePolicyRepository creates a new instance of MockGatePolicyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGatePolicyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGatePolicyRepository {
	mock := &MockGatePolicyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
