// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/sentiae/vigil/service/internal/port/repository"

	uuid "github.com/google/uuid"
)

// MockFindingRepository is an autogenerated mock type for the FindingRepository type
type MockFindingRepository struct {
	mock.Mock
}

type MockFindingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindingRepository) EXPECT() *MockFindingRepository_Expecter {
	return &MockFindingRepository_Expecter{mock: &_m.Mock}
}

// BulkUpsert provides a mock function with given fields: ctx, findings
func (_m *MockFindingRepository) BulkUpsert(ctx context.Context, findings []*domain.Finding) (int, int, error) {
	ret := _m.Called(ctx, findings)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Finding) (int, int, error)); ok {
		return rf(ctx, findings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Finding) int); ok {
		r0 = rf(ctx, findings)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*domain.Finding) int); ok {
		r1 = rf(ctx, findings)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []*domain.Finding) error); ok {
		r2 = rf(ctx, findings)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFindingRepository_BulkUpsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsert'
type MockFindingRepository_BulkUpsert_Call struct {
	*mock.Call
}

// BulkUpsert is a helper method to define mock.On call
//   - ctx context.Context
//   - findings []*domain.Finding
func (_e *MockFindingRepository_Expecter) BulkUpsert(ctx interface{}, findings interface{}) *MockFindingRepository_BulkUpsert_Call {
	return &MockFindingRepository_BulkUpsert_Call{Call: _e.mock.On("BulkUpsert", ctx, findings)}
}

func (_c *MockFindingRepository_BulkUpsert_Call) Run(run func(ctx context.Context, findings []*domain.Finding)) *MockFindingRepository_BulkUpsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.Finding))
	})
	return _c
}

func (_c *MockFindingRepository_BulkUpsert_Call) Return(created int, updated int, err error) *MockFindingRepository_BulkUpsert_Call {
	_c.Call.Return(created, updated, err)
	return _c
}

func (_c *MockFindingRepository_BulkUpsert_Call) RunAndReturn(run func(context.Context, []*domain.Finding) (int, int, error)) *MockFindingRepository_BulkUpsert_Call {
	_c.Call.Return(run)
	return _c
}

// CountBySeverity provides a mock function with given fields: ctx, tenantID
func (_m *MockFindingRepository) CountBySeverity(ctx context.Context, tenantID uuid.UUID) (map[domain.Severity]int, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for CountBySeverity")
	}

	var r0 map[domain.Severity]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[domain.Severity]int, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[domain.Severity]int); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.Severity]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingRepository_CountBySeverity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBySeverity'
type MockFindingRepository_CountBySeverity_Call struct {
	*mock.Call
}

// CountBySeverity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockFindingRepository_Expecter) CountBySeverity(ctx interface{}, tenantID interface{}) *MockFindingRepository_CountBySeverity_Call {
	return &MockFindingRepository_CountBySeverity_Call{Call: _e.mock.On("CountBySeverity", ctx, tenantID)}
}

func (_c *MockFindingRepository_CountBySeverity_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockFindingRepository_CountBySeverity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFindingRepository_CountBySeverity_Call) Return(_a0 map[domain.Severity]int, _a1 error) *MockFindingRepository_CountBySeverity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingRepository_CountBySeverity_Call) RunAndReturn(run func(context.Context, uuid.UUID) (map[domain.Severity]int, error)) *MockFindingRepository_CountBySeverity_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, finding
func (_m *MockFindingRepository) Create(ctx context.Context, finding *domain.Finding) error {
	ret := _m.Called(ctx, finding)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Finding) error); ok {
		r0 = rf(ctx, finding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFindingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFindingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - finding *domain.Finding
func (_e *MockFindingRepository_Expecter) Create(ctx interface{}, finding interface{}) *MockFindingRepository_Create_Call {
	return &MockFindingRepository_Create_Call{Call: _e.mock.On("Create", ctx, finding)}
}

func (_c *MockFindingRepository_Create_Call) Run(run func(ctx context.Context, finding *domain.Finding)) *MockFindingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Finding))
	})
	return _c
}

func (_c *MockFindingRepository_Create_Call) Return(_a0 error) *MockFindingRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFindingRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Finding) error) *MockFindingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFingerprint provides a mock function with given fields: ctx, tenantID, fingerprint
func (_m *MockFindingRepository) FindByFingerprint(ctx context.Context, tenantID uuid.UUID, fingerprint string) (*domain.Finding, error) {
	ret := _m.Called(ctx, tenantID, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for FindByFingerprint")
	}

	var r0 *domain.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.Finding, error)); ok {
		return rf(ctx, tenantID, fingerprint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.Finding); ok {
		r0 = rf(ctx, tenantID, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tenantID, fingerprint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingRepository_FindByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFingerprint'
type MockFindingRepository_FindByFingerprint_Call struct {
	*mock.Call
}

// FindByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - fingerprint string
func (_e *MockFindingRepository_Expecter) FindByFingerprint(ctx interface{}, tenantID interface{}, fingerprint interface{}) *MockFindingRepository_FindByFingerprint_Call {
	return &MockFindingRepository_FindByFingerprint_Call{Call: _e.mock.On("FindByFingerprint", ctx, tenantID, fingerprint)}
}

func (_c *MockFindingRepository_FindByFingerprint_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, fingerprint string)) *MockFindingRepository_FindByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockFindingRepository_FindByFingerprint_Call) Return(_a0 *domain.Finding, _a1 error) *MockFindingRepository_FindByFingerprint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingRepository_FindByFingerprint_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*domain.Finding, error)) *MockFindingRepository_FindByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenantID, id
func (_m *MockFindingRepository) FindByID(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Finding, error) {
	ret := _m.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Finding, error)); ok {
		return rf(ctx, tenantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Finding); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockFindingRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
func (_e *MockFindingRepository_Expecter) FindByID(ctx interface{}, tenantID interface{}, id interface{}) *MockFindingRepository_FindByID_Call {
	return &MockFindingRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenantID, id)}
}

func (_c *MockFindingRepository_FindByID_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID)) *MockFindingRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockFindingRepository_FindByID_Call) Return(_a0 *domain.Finding, _a1 error) *MockFindingRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Finding, error)) *MockFindingRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockFindingRepository) List(ctx context.Context, filter repository.FindingFilter) ([]*domain.Finding, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Finding
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindingFilter) ([]*domain.Finding, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindingFilter) []*domain.Finding); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.FindingFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.FindingFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFindingRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFindingRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.FindingFilter
func (_e *MockFindingRepository_Expecter) List(ctx interface{}, filter interface{}) *MockFindingRepository_List_Call {
	return &MockFindingRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockFindingRepository_List_Call) Run(run func(ctx context.Context, filter repository.FindingFilter)) *MockFindingRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.FindingFilter))
	})
	return _c
}

func (_c *MockFindingRepository_List_Call) Return(_a0 []*domain.Finding, _a1 int, _a2 error) *MockFindingRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFindingRepository_List_Call) RunAndReturn(run func(context.Context, repository.FindingFilter) ([]*domain.Finding, int, error)) *MockFindingRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveTenantIDs provides a mock function with given fields: ctx
func (_m *MockFindingRepository) ListActiveTenantIDs(ctx context.Context) ([]uuid.UUID, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveTenantIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]uuid.UUID, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []uuid.UUID); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingRepository_ListActiveTenantIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveTenantIDs'
type MockFindingRepository_ListActiveTenantIDs_Call struct {
	*mock.Call
}

// ListActiveTenantIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFindingRepository_Expecter) ListActiveTenantIDs(ctx interface{}) *MockFindingRepository_ListActiveTenantIDs_Call {
	return &MockFindingRepository_ListActiveTenantIDs_Call{Call: _e.mock.On("ListActiveTenantIDs", ctx)}
}

func (_c *MockFindingRepository_ListActiveTenantIDs_Call) Run(run func(ctx context.Context)) *MockFindingRepository_ListActiveTenantIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFindingRepository_ListActiveTenantIDs_Call) Return(_a0 []uuid.UUID, _a1 error) *MockFindingRepository_ListActiveTenantIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingRepository_ListActiveTenantIDs_Call) RunAndReturn(run func(context.Context) ([]uuid.UUID, error)) *MockFindingRepository_ListActiveTenantIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllSLABreached provides a mock function with given fields: ctx, limit
func (_m *MockFindingRepository) ListAllSLABreached(ctx context.Context, limit int) ([]*domain.Finding, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListAllSLABreached")
	}

	var r0 []*domain.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Finding, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Finding); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingRepository_ListAllSLABreached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllSLABreached'
type MockFindingRepository_ListAllSLABreached_Call struct {
	*mock.Call
}

// ListAllSLABreached is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockFindingRepository_Expecter) ListAllSLABreached(ctx interface{}, limit interface{}) *MockFindingRepository_ListAllSLABreached_Call {
	return &MockFindingRepository_ListAllSLABreached_Call{Call: _e.mock.On("ListAllSLABreached", ctx, limit)}
}

func (_c *MockFindingRepository_ListAllSLABreached_Call) Run(run func(ctx context.Context, limit int)) *MockFindingRepository_ListAllSLABreached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockFindingRepository_ListAllSLABreached_Call) Return(_a0 []*domain.Finding, _a1 error) *MockFindingRepository_ListAllSLABreached_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingRepository_ListAllSLABreached_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Finding, error)) *MockFindingRepository_ListAllSLABreached_Call {
	_c.Call.Return(run)
	return _c
}

// ListSLABreached provides a mock function with given fields: ctx, tenantID
func (_m *MockFindingRepository) ListSLABreached(ctx context.Context, tenantID uuid.UUID) ([]*domain.Finding, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for ListSLABreached")
	}

	var r0 []*domain.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Finding, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Finding); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingRepository_ListSLABreached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLABreached'
type MockFindingRepository_ListSLABreached_Call struct {
	*mock.Call
}

// ListSLABreached is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockFindingRepository_Expecter) ListSLABreached(ctx interface{}, tenantID interface{}) *MockFindingRepository_ListSLABreached_Call {
	return &MockFindingRepository_ListSLABreached_Call{Call: _e.mock.On("ListSLABreached", ctx, tenantID)}
}

func (_c *MockFindingRepository_ListSLABreached_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockFindingRepository_ListSLABreached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFindingRepository_ListSLABreached_Call) Return(_a0 []*domain.Finding, _a1 error) *MockFindingRepository_ListSLABreached_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingRepository_ListSLABreached_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Finding, error)) *MockFindingRepository_ListSLABreached_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, finding
func (_m *MockFindingRepository) Update(ctx context.Context, finding *domain.Finding) error {
	ret := _m.Called(ctx, finding)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Finding) error); ok {
		r0 = rf(ctx, finding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFindingRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFindingRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - finding *domain.Finding
func (_e *MockFindingRepository_Expecter) Update(ctx interface{}, finding interface{}) *MockFindingRepository_Update_Call {
	return &MockFindingRepository_Update_Call{Call: _e.mock.On("Update", ctx, finding)}
}

func (_c *MockFindingRepository_Update_Call) Run(run func(ctx context.Context, finding *domain.Finding)) *MockFindingRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Finding))
	})
	return _c
}

func (_c *MockFindingRepository_Update_Call) Return(_a0 error) *MockFindingRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFindingRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Finding) error) *MockFindingRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastSeen provides a mock function with given fields: ctx, tenantID, fingerprint
func (_m *MockFindingRepository) UpdateLastSeen(ctx context.Context, tenantID uuid.UUID, fingerprint string) error {
	ret := _m.Called(ctx, tenantID, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tenantID, fingerprint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFindingRepository_UpdateLastSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastSeen'
type MockFindingRepository_UpdateLastSeen_Call struct {
	*mock.Call
}

// UpdateLastSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - fingerprint string
func (_e *MockFindingRepository_Expecter) UpdateLastSeen(ctx interface{}, tenantID interface{}, fingerprint interface{}) *MockFindingRepository_UpdateLastSeen_Call {
	return &MockFindingRepository_UpdateLastSeen_Call{Call: _e.mock.On("UpdateLastSeen", ctx, tenantID, fingerprint)}
}

func (_c *MockFindingRepository_UpdateLastSeen_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, fingerprint string)) *MockFindingRepository_UpdateLastSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockFindingRepository_UpdateLastSeen_Call) Return(_a0 error) *MockFindingRepository_UpdateLastSeen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFindingRepository_UpdateLastSeen_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockFindingRepository_UpdateLastSeen_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, tenantID, id, status
func (_m *MockFindingRepository) UpdateStatus(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, status domain.FindingStatus) error {
	ret := _m.Called(ctx, tenantID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.FindingStatus) error); ok {
		r0 = rf(ctx, tenantID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFindingRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockFindingRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
//   - status domain.FindingStatus
func (_e *MockFindingRepository_Expecter) UpdateStatus(ctx interface{}, tenantID interface{}, id interface{}, status interface{}) *MockFindingRepository_UpdateStatus_Call {
	return &MockFindingRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, tenantID, id, status)}
}

func (_c *MockFindingRepository_UpdateStatus_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, status domain.FindingStatus)) *MockFindingRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(domain.FindingStatus))
	})
	return _c
}

func (_c *MockFindingRepository_UpdateStatus_Call) Return(_a0 error) *MockFindingRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFindingRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, domain.FindingStatus) error) *MockFindingRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFindingRepository creates a new instance of MockFindingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindingRepository {
	mock := &MockFindingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
