// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/sentiae/vigil/service/internal/port/repository"

	usecase "github.com/sentiae/vigil/service/internal/port/usecase"

	uuid "github.com/google/uuid"
)

// MockScanUseCase is an autogenerated mock type for the ScanUseCase type
type MockScanUseCase struct {
	mock.Mock
}

type MockScanUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanUseCase) EXPECT() *MockScanUseCase_Expecter {
	return &MockScanUseCase_Expecter{mock: &_m.Mock}
}

// GetScan provides a mock function with given fields: ctx, tenantID, id
func (_m *MockScanUseCase) GetScan(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Scan, error) {
	ret := _m.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetScan")
	}

	var r0 *domain.Scan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Scan, error)); ok {
		return rf(ctx, tenantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Scan); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Scan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanUseCase_GetScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScan'
type MockScanUseCase_GetScan_Call struct {
	*mock.Call
}

// GetScan is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
func (_e *MockScanUseCase_Expecter) GetScan(ctx interface{}, tenantID interface{}, id interface{}) *MockScanUseCase_GetScan_Call {
	return &MockScanUseCase_GetScan_Call{Call: _e.mock.On("GetScan", ctx, tenantID, id)}
}

func (_c *MockScanUseCase_GetScan_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID)) *MockScanUseCase_GetScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockScanUseCase_GetScan_Call) Return(_a0 *domain.Scan, _a1 error) *MockScanUseCase_GetScan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanUseCase_GetScan_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Scan, error)) *MockScanUseCase_GetScan_Call {
	_c.Call.Return(run)
	return _c
}

// ListScans provides a mock function with given fields: ctx, filter
func (_m *MockScanUseCase) ListScans(ctx context.Context, filter repository.ScanFilter) ([]*domain.Scan, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListScans")
	}

	var r0 []*domain.Scan
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ScanFilter) ([]*domain.Scan, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ScanFilter) []*domain.Scan); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Scan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ScanFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ScanFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockScanUseCase_ListScans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScans'
type MockScanUseCase_ListScans_Call struct {
	*mock.Call
}

// ListScans is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.ScanFilter
func (_e *MockScanUseCase_Expecter) ListScans(ctx interface{}, filter interface{}) *MockScanUseCase_ListScans_Call {
	return &MockScanUseCase_ListScans_Call{Call: _e.mock.On("ListScans", ctx, filter)}
}

func (_c *MockScanUseCase_ListScans_Call) Run(run func(ctx context.Context, filter repository.ScanFilter)) *MockScanUseCase_ListScans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ScanFilter))
	})
	return _c
}

func (_c *MockScanUseCase_ListScans_Call) Return(_a0 []*domain.Scan, _a1 int, _a2 error) *MockScanUseCase_ListScans_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockScanUseCase_ListScans_Call) RunAndReturn(run func(context.Context, repository.ScanFilter) ([]*domain.Scan, int, error)) *MockScanUseCase_ListScans_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerScan provides a mock function with given fields: ctx, input
func (_m *MockScanUseCase) TriggerScan(ctx context.Context, input usecase.TriggerScanInput) (*domain.Scan, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for TriggerScan")
	}

	var r0 *domain.Scan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.TriggerScanInput) (*domain.Scan, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.TriggerScanInput) *domain.Scan); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Scan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.TriggerScanInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanUseCase_TriggerScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerScan'
type MockScanUseCase_TriggerScan_Call struct {
	*mock.Call
}

// TriggerScan is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.TriggerScanInput
func (_e *MockScanUseCase_Expecter) TriggerScan(ctx interface{}, input interface{}) *MockScanUseCase_TriggerScan_Call {
	return &MockScanUseCase_TriggerScan_Call{Call: _e.mock.On("TriggerScan", ctx, input)}
}

func (_c *MockScanUseCase_TriggerScan_Call) Run(run func(ctx context.Context, input usecase.TriggerScanInput)) *MockScanUseCase_TriggerScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.TriggerScanInput))
	})
	return _c
}

func (_c *MockScanUseCase_TriggerScan_Call) Return(_a0 *domain.Scan, _a1 error) *MockScanUseCase_TriggerScan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanUseCase_TriggerScan_Call) RunAndReturn(run func(context.Context, usecase.TriggerScanInput) (*domain.Scan, error)) *MockScanUseCase_TriggerScan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScanUseCase creates a new instance of MockScanUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanUseCase {
	mock := &MockScanUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
