// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/sentiae/vigil/service/internal/port/repository"

	usecase "github.com/sentiae/vigil/service/internal/port/usecase"

	uuid "github.com/google/uuid"
)

// MockFindingUseCase is an autogenerated mock type for the FindingUseCase type
type MockFindingUseCase struct {
	mock.Mock
}

type MockFindingUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFindingUseCase) EXPECT() *MockFindingUseCase_Expecter {
	return &MockFindingUseCase_Expecter{mock: &_m.Mock}
}

// CountBySeverity provides a mock function with given fields: ctx, tenantID
func (_m *MockFindingUseCase) CountBySeverity(ctx context.Context, tenantID uuid.UUID) (map[domain.Severity]int, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for CountBySeverity")
	}

	var r0 map[domain.Severity]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[domain.Severity]int, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[domain.Severity]int); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.Severity]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingUseCase_CountBySeverity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBySeverity'
type MockFindingUseCase_CountBySeverity_Call struct {
	*mock.Call
}

// CountBySeverity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockFindingUseCase_Expecter) CountBySeverity(ctx interface{}, tenantID interface{}) *MockFindingUseCase_CountBySeverity_Call {
	return &MockFindingUseCase_CountBySeverity_Call{Call: _e.mock.On("CountBySeverity", ctx, tenantID)}
}

func (_c *MockFindingUseCase_CountBySeverity_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockFindingUseCase_CountBySeverity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFindingUseCase_CountBySeverity_Call) Return(_a0 map[domain.Severity]int, _a1 error) *MockFindingUseCase_CountBySeverity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingUseCase_CountBySeverity_Call) RunAndReturn(run func(context.Context, uuid.UUID) (map[domain.Severity]int, error)) *MockFindingUseCase_CountBySeverity_Call {
	_c.Call.Return(run)
	return _c
}

// GetFinding provides a mock function with given fields: ctx, tenantID, id
func (_m *MockFindingUseCase) GetFinding(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Finding, error) {
	ret := _m.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFinding")
	}

	var r0 *domain.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Finding, error)); ok {
		return rf(ctx, tenantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Finding); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingUseCase_GetFinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFinding'
type MockFindingUseCase_GetFinding_Call struct {
	*mock.Call
}

// GetFinding is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
func (_e *MockFindingUseCase_Expecter) GetFinding(ctx interface{}, tenantID interface{}, id interface{}) *MockFindingUseCase_GetFinding_Call {
	return &MockFindingUseCase_GetFinding_Call{Call: _e.mock.On("GetFinding", ctx, tenantID, id)}
}

func (_c *MockFindingUseCase_GetFinding_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID)) *MockFindingUseCase_GetFinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockFindingUseCase_GetFinding_Call) Return(_a0 *domain.Finding, _a1 error) *MockFindingUseCase_GetFinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingUseCase_GetFinding_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Finding, error)) *MockFindingUseCase_GetFinding_Call {
	_c.Call.Return(run)
	return _c
}

// IngestFindings provides a mock function with given fields: ctx, tenantID, findings
func (_m *MockFindingUseCase) IngestFindings(ctx context.Context, tenantID uuid.UUID, findings []*domain.Finding) (int, int, error) {
	ret := _m.Called(ctx, tenantID, findings)

	if len(ret) == 0 {
		panic("no return value specified for IngestFindings")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []*domain.Finding) (int, int, error)); ok {
		return rf(ctx, tenantID, findings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []*domain.Finding) int); ok {
		r0 = rf(ctx, tenantID, findings)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []*domain.Finding) int); ok {
		r1 = rf(ctx, tenantID, findings)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, []*domain.Finding) error); ok {
		r2 = rf(ctx, tenantID, findings)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFindingUseCase_IngestFindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestFindings'
type MockFindingUseCase_IngestFindings_Call struct {
	*mock.Call
}

// IngestFindings is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - findings []*domain.Finding
func (_e *MockFindingUseCase_Expecter) IngestFindings(ctx interface{}, tenantID interface{}, findings interface{}) *MockFindingUseCase_IngestFindings_Call {
	return &MockFindingUseCase_IngestFindings_Call{Call: _e.mock.On("IngestFindings", ctx, tenantID, findings)}
}

func (_c *MockFindingUseCase_IngestFindings_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, findings []*domain.Finding)) *MockFindingUseCase_IngestFindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]*domain.Finding))
	})
	return _c
}

func (_c *MockFindingUseCase_IngestFindings_Call) Return(created int, updated int, err error) *MockFindingUseCase_IngestFindings_Call {
	_c.Call.Return(created, updated, err)
	return _c
}

func (_c *MockFindingUseCase_IngestFindings_Call) RunAndReturn(run func(context.Context, uuid.UUID, []*domain.Finding) (int, int, error)) *MockFindingUseCase_IngestFindings_Call {
	_c.Call.Return(run)
	return _c
}

// ListFindings provides a mock function with given fields: ctx, filter
func (_m *MockFindingUseCase) ListFindings(ctx context.Context, filter repository.FindingFilter) ([]*domain.Finding, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListFindings")
	}

	var r0 []*domain.Finding
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindingFilter) ([]*domain.Finding, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindingFilter) []*domain.Finding); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.FindingFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.FindingFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFindingUseCase_ListFindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFindings'
type MockFindingUseCase_ListFindings_Call struct {
	*mock.Call
}

// ListFindings is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.FindingFilter
func (_e *MockFindingUseCase_Expecter) ListFindings(ctx interface{}, filter interface{}) *MockFindingUseCase_ListFindings_Call {
	return &MockFindingUseCase_ListFindings_Call{Call: _e.mock.On("ListFindings", ctx, filter)}
}

func (_c *MockFindingUseCase_ListFindings_Call) Run(run func(ctx context.Context, filter repository.FindingFilter)) *MockFindingUseCase_ListFindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.FindingFilter))
	})
	return _c
}

func (_c *MockFindingUseCase_ListFindings_Call) Return(_a0 []*domain.Finding, _a1 int, _a2 error) *MockFindingUseCase_ListFindings_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFindingUseCase_ListFindings_Call) RunAndReturn(run func(context.Context, repository.FindingFilter) ([]*domain.Finding, int, error)) *MockFindingUseCase_ListFindings_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveFinding provides a mock function with given fields: ctx, tenantID, input
func (_m *MockFindingUseCase) ResolveFinding(ctx context.Context, tenantID uuid.UUID, input usecase.ResolveFindingInput) (*domain.Finding, error) {
	ret := _m.Called(ctx, tenantID, input)

	if len(ret) == 0 {
		panic("no return value specified for ResolveFinding")
	}

	var r0 *domain.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, usecase.ResolveFindingInput) (*domain.Finding, error)); ok {
		return rf(ctx, tenantID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, usecase.ResolveFindingInput) *domain.Finding); ok {
		r0 = rf(ctx, tenantID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, usecase.ResolveFindingInput) error); ok {
		r1 = rf(ctx, tenantID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFindingUseCase_ResolveFinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveFinding'
type MockFindingUseCase_ResolveFinding_Call struct {
	*mock.Call
}

// ResolveFinding is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - input usecase.ResolveFindingInput
func (_e *MockFindingUseCase_Expecter) ResolveFinding(ctx interface{}, tenantID interface{}, input interface{}) *MockFindingUseCase_ResolveFinding_Call {
	return &MockFindingUseCase_ResolveFinding_Call{Call: _e.mock.On("ResolveFinding", ctx, tenantID, input)}
}

func (_c *MockFindingUseCase_ResolveFinding_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, input usecase.ResolveFindingInput)) *MockFindingUseCase_ResolveFinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(usecase.ResolveFindingInput))
	})
	return _c
}

func (_c *MockFindingUseCase_ResolveFinding_Call) Return(_a0 *domain.Finding, _a1 error) *MockFindingUseCase_ResolveFinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFindingUseCase_ResolveFinding_Call) RunAndReturn(run func(context.Context, uuid.UUID, usecase.ResolveFindingInput) (*domain.Finding, error)) *MockFindingUseCase_ResolveFinding_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFindingUseCase creates a new instance of MockFindingUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFindingUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFindingUseCase {
	mock := &MockFindingUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
