// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/sentiae/vigil/service/internal/port/repository"

	uuid "github.com/google/uuid"
)

// MockAssetRepository is an autogenerated mock type for the AssetRepository type
type MockAssetRepository struct {
	mock.Mock
}

type MockAssetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssetRepository) EXPECT() *MockAssetRepository_Expecter {
	return &MockAssetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, asset
func (_m *MockAssetRepository) Create(ctx context.Context, asset *domain.Asset) error {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Asset) error); ok {
		r0 = rf(ctx, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAssetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAssetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - asset *domain.Asset
func (_e *MockAssetRepository_Expecter) Create(ctx interface{}, asset interface{}) *MockAssetRepository_Create_Call {
	return &MockAssetRepository_Create_Call{Call: _e.mock.On("Create", ctx, asset)}
}

func (_c *MockAssetRepository_Create_Call) Run(run func(ctx context.Context, asset *domain.Asset)) *MockAssetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Asset))
	})
	return _c
}

func (_c *MockAssetRepository_Create_Call) Return(_a0 error) *MockAssetRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAssetRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Asset) error) *MockAssetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByARN provides a mock function with given fields: ctx, tenantID, arn
func (_m *MockAssetRepository) FindByARN(ctx context.Context, tenantID uuid.UUID, arn string) (*domain.Asset, error) {
	ret := _m.Called(ctx, tenantID, arn)

	if len(ret) == 0 {
		panic("no return value specified for FindByARN")
	}

	var r0 *domain.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.Asset, error)); ok {
		return rf(ctx, tenantID, arn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.Asset); ok {
		r0 = rf(ctx, tenantID, arn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tenantID, arn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAssetRepository_FindByARN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByARN'
type MockAssetRepository_FindByARN_Call struct {
	*mock.Call
}

// FindByARN is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - arn string
func (_e *MockAssetRepository_Expecter) FindByARN(ctx interface{}, tenantID interface{}, arn interface{}) *MockAssetRepository_FindByARN_Call {
	return &MockAssetRepository_FindByARN_Call{Call: _e.mock.On("FindByARN", ctx, tenantID, arn)}
}

func (_c *MockAssetRepository_FindByARN_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, arn string)) *MockAssetRepository_FindByARN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockAssetRepository_FindByARN_Call) Return(_a0 *domain.Asset, _a1 error) *MockAssetRepository_FindByARN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAssetRepository_FindByARN_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*domain.Asset, error)) *MockAssetRepository_FindByARN_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenantID, id
func (_m *MockAssetRepository) FindByID(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Asset, error) {
	ret := _m.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Asset, error)); ok {
		return rf(ctx, tenantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Asset); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAssetRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAssetRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
func (_e *MockAssetRepository_Expecter) FindByID(ctx interface{}, tenantID interface{}, id interface{}) *MockAssetRepository_FindByID_Call {
	return &MockAssetRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenantID, id)}
}

func (_c *MockAssetRepository_FindByID_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID)) *MockAssetRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAssetRepository_FindByID_Call) Return(_a0 *domain.Asset, _a1 error) *MockAssetRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAssetRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Asset, error)) *MockAssetRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockAssetRepository) List(ctx context.Context, filter repository.AssetFilter) ([]*domain.Asset, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Asset
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AssetFilter) ([]*domain.Asset, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AssetFilter) []*domain.Asset); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AssetFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.AssetFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAssetRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAssetRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.AssetFilter
func (_e *MockAssetRepository_Expecter) List(ctx interface{}, filter interface{}) *MockAssetRepository_List_Call {
	return &MockAssetRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockAssetRepository_List_Call) Run(run func(ctx context.Context, filter repository.AssetFilter)) *MockAssetRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AssetFilter))
	})
	return _c
}

func (_c *MockAssetRepository_List_Call) Return(_a0 []*domain.Asset, _a1 int, _a2 error) *MockAssetRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAssetRepository_List_Call) RunAndReturn(run func(context.Context, repository.AssetFilter) ([]*domain.Asset, int, error)) *MockAssetRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, asset
func (_m *MockAssetRepository) Update(ctx context.Context, asset *domain.Asset) error {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Asset) error); ok {
		r0 = rf(ctx, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAssetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAssetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - asset *domain.Asset
func (_e *MockAssetRepository_Expecter) Update(ctx interface{}, asset interface{}) *MockAssetRepository_Update_Call {
	return &MockAssetRepository_Update_Call{Call: _e.mock.On("Update", ctx, asset)}
}

func (_c *MockAssetRepository_Update_Call) Run(run func(ctx context.Context, asset *domain.Asset)) *MockAssetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Asset))
	})
	return _c
}

func (_c *MockAssetRepository_Update_Call) Return(_a0 error) *MockAssetRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAssetRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Asset) error) *MockAssetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAssetRepository creates a new instance of MockAssetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssetRepository {
	mock := &MockAssetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
