// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	scanner "github.com/sentiae/vigil/service/internal/port/scanner"
)

// MockScanner is an autogenerated mock type for the Scanner type
type MockScanner struct {
	mock.Mock
}

type MockScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanner) EXPECT() *MockScanner_Expecter {
	return &MockScanner_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *MockScanner) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockScanner_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockScanner_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockScanner_Expecter) Name() *MockScanner_Name_Call {
	return &MockScanner_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockScanner_Name_Call) Run(run func()) *MockScanner_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScanner_Name_Call) Return(_a0 string) *MockScanner_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanner_Name_Call) RunAndReturn(run func() string) *MockScanner_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: ctx, target
func (_m *MockScanner) Scan(ctx context.Context, target scanner.ScanTarget) ([]*domain.Finding, error) {
	ret := _m.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 []*domain.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, scanner.ScanTarget) ([]*domain.Finding, error)); ok {
		return rf(ctx, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, scanner.ScanTarget) []*domain.Finding); ok {
		r0 = rf(ctx, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, scanner.ScanTarget) error); ok {
		r1 = rf(ctx, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanner_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockScanner_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - target scanner.ScanTarget
func (_e *MockScanner_Expecter) Scan(ctx interface{}, target interface{}) *MockScanner_Scan_Call {
	return &MockScanner_Scan_Call{Call: _e.mock.On("Scan", ctx, target)}
}

func (_c *MockScanner_Scan_Call) Run(run func(ctx context.Context, target scanner.ScanTarget)) *MockScanner_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(scanner.ScanTarget))
	})
	return _c
}

func (_c *MockScanner_Scan_Call) Return(_a0 []*domain.Finding, _a1 error) *MockScanner_Scan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanner_Scan_Call) RunAndReturn(run func(context.Context, scanner.ScanTarget) ([]*domain.Finding, error)) *MockScanner_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// Supports provides a mock function with given fields: target
func (_m *MockScanner) Supports(target scanner.ScanTarget) bool {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Supports")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(scanner.ScanTarget) bool); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockScanner_Supports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Supports'
type MockScanner_Supports_Call struct {
	*mock.Call
}

// Supports is a helper method to define mock.On call
//   - target scanner.ScanTarget
func (_e *MockScanner_Expecter) Supports(target interface{}) *MockScanner_Supports_Call {
	return &MockScanner_Supports_Call{Call: _e.mock.On("Supports", target)}
}

func (_c *MockScanner_Supports_Call) Run(run func(target scanner.ScanTarget)) *MockScanner_Supports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(scanner.ScanTarget))
	})
	return _c
}

func (_c *MockScanner_Supports_Call) Return(_a0 bool) *MockScanner_Supports_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanner_Supports_Call) RunAndReturn(run func(scanner.ScanTarget) bool) *MockScanner_Supports_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockScanner) Type() domain.AnalysisType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 domain.AnalysisType
	if rf, ok := ret.Get(0).(func() domain.AnalysisType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.AnalysisType)
	}

	return r0
}

// MockScanner_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockScanner_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockScanner_Expecter) Type() *MockScanner_Type_Call {
	return &MockScanner_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockScanner_Type_Call) Run(run func()) *MockScanner_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScanner_Type_Call) Return(_a0 domain.AnalysisType) *MockScanner_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanner_Type_Call) RunAndReturn(run func() domain.AnalysisType) *MockScanner_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScanner creates a new instance of MockScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanner {
	mock := &MockScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
