// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/sentiae/vigil/service/internal/port/repository"

	uuid "github.com/google/uuid"
)

// MockGraphRepository is an autogenerated mock type for the GraphRepository type
type MockGraphRepository struct {
	mock.Mock
}

type MockGraphRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGraphRepository) EXPECT() *MockGraphRepository_Expecter {
	return &MockGraphRepository_Expecter{mock: &_m.Mock}
}

// AttackPaths provides a mock function with given fields: ctx, tenantID, assetID
func (_m *MockGraphRepository) AttackPaths(ctx context.Context, tenantID uuid.UUID, assetID uuid.UUID) ([]*repository.AttackPath, error) {
	ret := _m.Called(ctx, tenantID, assetID)

	if len(ret) == 0 {
		panic("no return value specified for AttackPaths")
	}

	var r0 []*repository.AttackPath
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*repository.AttackPath, error)); ok {
		return rf(ctx, tenantID, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*repository.AttackPath); ok {
		r0 = rf(ctx, tenantID, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.AttackPath)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGraphRepository_AttackPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttackPaths'
type MockGraphRepository_AttackPaths_Call struct {
	*mock.Call
}

// AttackPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - assetID uuid.UUID
func (_e *MockGraphRepository_Expecter) AttackPaths(ctx interface{}, tenantID interface{}, assetID interface{}) *MockGraphRepository_AttackPaths_Call {
	return &MockGraphRepository_AttackPaths_Call{Call: _e.mock.On("AttackPaths", ctx, tenantID, assetID)}
}

func (_c *MockGraphRepository_AttackPaths_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, assetID uuid.UUID)) *MockGraphRepository_AttackPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGraphRepository_AttackPaths_Call) Return(_a0 []*repository.AttackPath, _a1 error) *MockGraphRepository_AttackPaths_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGraphRepository_AttackPaths_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]*repository.AttackPath, error)) *MockGraphRepository_AttackPaths_Call {
	_c.Call.Return(run)
	return _c
}

// BlastRadius provides a mock function with given fields: ctx, tenantID, assetID, maxDepth
func (_m *MockGraphRepository) BlastRadius(ctx context.Context, tenantID uuid.UUID, assetID uuid.UUID, maxDepth int) (*repository.BlastRadius, error) {
	ret := _m.Called(ctx, tenantID, assetID, maxDepth)

	if len(ret) == 0 {
		panic("no return value specified for BlastRadius")
	}

	var r0 *repository.BlastRadius
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) (*repository.BlastRadius, error)); ok {
		return rf(ctx, tenantID, assetID, maxDepth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) *repository.BlastRadius); ok {
		r0 = rf(ctx, tenantID, assetID, maxDepth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.BlastRadius)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r1 = rf(ctx, tenantID, assetID, maxDepth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGraphRepository_BlastRadius_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlastRadius'
type MockGraphRepository_BlastRadius_Call struct {
	*mock.Call
}

// BlastRadius is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - assetID uuid.UUID
//   - maxDepth int
func (_e *MockGraphRepository_Expecter) BlastRadius(ctx interface{}, tenantID interface{}, assetID interface{}, maxDepth interface{}) *MockGraphRepository_BlastRadius_Call {
	return &MockGraphRepository_BlastRadius_Call{Call: _e.mock.On("BlastRadius", ctx, tenantID, assetID, maxDepth)}
}

func (_c *MockGraphRepository_BlastRadius_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, assetID uuid.UUID, maxDepth int)) *MockGraphRepository_BlastRadius_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockGraphRepository_BlastRadius_Call) Return(_a0 *repository.BlastRadius, _a1 error) *MockGraphRepository_BlastRadius_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGraphRepository_BlastRadius_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int) (*repository.BlastRadius, error)) *MockGraphRepository_BlastRadius_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAsset provides a mock function with given fields: ctx, asset
func (_m *MockGraphRepository) CreateAsset(ctx context.Context, asset *domain.Asset) error {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for CreateAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Asset) error); ok {
		r0 = rf(ctx, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGraphRepository_CreateAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAsset'
type MockGraphRepository_CreateAsset_Call struct {
	*mock.Call
}

// CreateAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - asset *domain.Asset
func (_e *MockGraphRepository_Expecter) CreateAsset(ctx interface{}, asset interface{}) *MockGraphRepository_CreateAsset_Call {
	return &MockGraphRepository_CreateAsset_Call{Call: _e.mock.On("CreateAsset", ctx, asset)}
}

func (_c *MockGraphRepository_CreateAsset_Call) Run(run func(ctx context.Context, asset *domain.Asset)) *MockGraphRepository_CreateAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Asset))
	})
	return _c
}

func (_c *MockGraphRepository_CreateAsset_Call) Return(_a0 error) *MockGraphRepository_CreateAsset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGraphRepository_CreateAsset_Call) RunAndReturn(run func(context.Context, *domain.Asset) error) *MockGraphRepository_CreateAsset_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRelationship provides a mock function with given fields: ctx, rel
func (_m *MockGraphRepository) CreateRelationship(ctx context.Context, rel repository.AssetRelationship) error {
	ret := _m.Called(ctx, rel)

	if len(ret) == 0 {
		panic("no return value specified for CreateRelationship")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AssetRelationship) error); ok {
		r0 = rf(ctx, rel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGraphRepository_CreateRelationship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRelationship'
type MockGraphRepository_CreateRelationship_Call struct {
	*mock.Call
}

// CreateRelationship is a helper method to define mock.On call
//   - ctx context.Context
//   - rel repository.AssetRelationship
func (_e *MockGraphRepository_Expecter) CreateRelationship(ctx interface{}, rel interface{}) *MockGraphRepository_CreateRelationship_Call {
	return &MockGraphRepository_CreateRelationship_Call{Call: _e.mock.On("CreateRelationship", ctx, rel)}
}

func (_c *MockGraphRepository_CreateRelationship_Call) Run(run func(ctx context.Context, rel repository.AssetRelationship)) *MockGraphRepository_CreateRelationship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AssetRelationship))
	})
	return _c
}

func (_c *MockGraphRepository_CreateRelationship_Call) Return(_a0 error) *MockGraphRepository_CreateRelationship_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGraphRepository_CreateRelationship_Call) RunAndReturn(run func(context.Context, repository.AssetRelationship) error) *MockGraphRepository_CreateRelationship_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAsset provides a mock function with given fields: ctx, asset
func (_m *MockGraphRepository) UpdateAsset(ctx context.Context, asset *domain.Asset) error {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Asset) error); ok {
		r0 = rf(ctx, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGraphRepository_UpdateAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAsset'
type MockGraphRepository_UpdateAsset_Call struct {
	*mock.Call
}

// UpdateAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - asset *domain.Asset
func (_e *MockGraphRepository_Expecter) UpdateAsset(ctx interface{}, asset interface{}) *MockGraphRepository_UpdateAsset_Call {
	return &MockGraphRepository_UpdateAsset_Call{Call: _e.mock.On("UpdateAsset", ctx, asset)}
}

func (_c *MockGraphRepository_UpdateAsset_Call) Run(run func(ctx context.Context, asset *domain.Asset)) *MockGraphRepository_UpdateAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Asset))
	})
	return _c
}

func (_c *MockGraphRepository_UpdateAsset_Call) Return(_a0 error) *MockGraphRepository_UpdateAsset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGraphRepository_UpdateAsset_Call) RunAndReturn(run func(context.Context, *domain.Asset) error) *MockGraphRepository_UpdateAsset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGraphRepository creates a new instance of MockGraphRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphRepository {
	mock := &MockGraphRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
