// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockComplianceUseCase is an autogenerated mock type for the ComplianceUseCase type
type MockComplianceUseCase struct {
	mock.Mock
}

type MockComplianceUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComplianceUseCase) EXPECT() *MockComplianceUseCase_Expecter {
	return &MockComplianceUseCase_Expecter{mock: &_m.Mock}
}

// GetAssetPosture provides a mock function with given fields: ctx, tenantID, assetID
func (_m *MockComplianceUseCase) GetAssetPosture(ctx context.Context, tenantID uuid.UUID, assetID uuid.UUID) (*domain.AssetSecurityPosture, error) {
	ret := _m.Called(ctx, tenantID, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetPosture")
	}

	var r0 *domain.AssetSecurityPosture
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.AssetSecurityPosture, error)); ok {
		return rf(ctx, tenantID, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.AssetSecurityPosture); ok {
		r0 = rf(ctx, tenantID, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AssetSecurityPosture)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComplianceUseCase_GetAssetPosture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetPosture'
type MockComplianceUseCase_GetAssetPosture_Call struct {
	*mock.Call
}

// GetAssetPosture is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - assetID uuid.UUID
func (_e *MockComplianceUseCase_Expecter) GetAssetPosture(ctx interface{}, tenantID interface{}, assetID interface{}) *MockComplianceUseCase_GetAssetPosture_Call {
	return &MockComplianceUseCase_GetAssetPosture_Call{Call: _e.mock.On("GetAssetPosture", ctx, tenantID, assetID)}
}

func (_c *MockComplianceUseCase_GetAssetPosture_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, assetID uuid.UUID)) *MockComplianceUseCase_GetAssetPosture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockComplianceUseCase_GetAssetPosture_Call) Return(_a0 *domain.AssetSecurityPosture, _a1 error) *MockComplianceUseCase_GetAssetPosture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComplianceUseCase_GetAssetPosture_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.AssetSecurityPosture, error)) *MockComplianceUseCase_GetAssetPosture_Call {
	_c.Call.Return(run)
	return _c
}

// GetComplianceSummary provides a mock function with given fields: ctx, tenantID
func (_m *MockComplianceUseCase) GetComplianceSummary(ctx context.Context, tenantID uuid.UUID) (*domain.ComplianceSummary, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetComplianceSummary")
	}

	var r0 *domain.ComplianceSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ComplianceSummary, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ComplianceSummary); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ComplianceSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComplianceUseCase_GetComplianceSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComplianceSummary'
type MockComplianceUseCase_GetComplianceSummary_Call struct {
	*mock.Call
}

// GetComplianceSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockComplianceUseCase_Expecter) GetComplianceSummary(ctx interface{}, tenantID interface{}) *MockComplianceUseCase_GetComplianceSummary_Call {
	return &MockComplianceUseCase_GetComplianceSummary_Call{Call: _e.mock.On("GetComplianceSummary", ctx, tenantID)}
}

func (_c *MockComplianceUseCase_GetComplianceSummary_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockComplianceUseCase_GetComplianceSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockComplianceUseCase_GetComplianceSummary_Call) Return(_a0 *domain.ComplianceSummary, _a1 error) *MockComplianceUseCase_GetComplianceSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComplianceUseCase_GetComplianceSummary_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.ComplianceSummary, error)) *MockComplianceUseCase_GetComplianceSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComplianceUseCase creates a new instance of MockComplianceUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComplianceUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComplianceUseCase {
	mock := &MockComplianceUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
