// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sentiae/vigil/service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/sentiae/vigil/service/internal/port/repository"

	uuid "github.com/google/uuid"
)

// MockScanRepository is an autogenerated mock type for the ScanRepository type
type MockScanRepository struct {
	mock.Mock
}

type MockScanRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanRepository) EXPECT() *MockScanRepository_Expecter {
	return &MockScanRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, scan
func (_m *MockScanRepository) Create(ctx context.Context, scan *domain.Scan) error {
	ret := _m.Called(ctx, scan)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Scan) error); ok {
		r0 = rf(ctx, scan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScanRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockScanRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - scan *domain.Scan
func (_e *MockScanRepository_Expecter) Create(ctx interface{}, scan interface{}) *MockScanRepository_Create_Call {
	return &MockScanRepository_Create_Call{Call: _e.mock.On("Create", ctx, scan)}
}

func (_c *MockScanRepository_Create_Call) Run(run func(ctx context.Context, scan *domain.Scan)) *MockScanRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Scan))
	})
	return _c
}

func (_c *MockScanRepository_Create_Call) Return(_a0 error) *MockScanRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Scan) error) *MockScanRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, tenantID, id
func (_m *MockScanRepository) FindByID(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) (*domain.Scan, error) {
	ret := _m.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Scan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Scan, error)); ok {
		return rf(ctx, tenantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Scan); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Scan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockScanRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
func (_e *MockScanRepository_Expecter) FindByID(ctx interface{}, tenantID interface{}, id interface{}) *MockScanRepository_FindByID_Call {
	return &MockScanRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, tenantID, id)}
}

func (_c *MockScanRepository_FindByID_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID)) *MockScanRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockScanRepository_FindByID_Call) Return(_a0 *domain.Scan, _a1 error) *MockScanRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Scan, error)) *MockScanRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockScanRepository) List(ctx context.Context, filter repository.ScanFilter) ([]*domain.Scan, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Scan
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ScanFilter) ([]*domain.Scan, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ScanFilter) []*domain.Scan); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Scan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ScanFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ScanFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockScanRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockScanRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.ScanFilter
func (_e *MockScanRepository_Expecter) List(ctx interface{}, filter interface{}) *MockScanRepository_List_Call {
	return &MockScanRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockScanRepository_List_Call) Run(run func(ctx context.Context, filter repository.ScanFilter)) *MockScanRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ScanFilter))
	})
	return _c
}

func (_c *MockScanRepository_List_Call) Return(_a0 []*domain.Scan, _a1 int, _a2 error) *MockScanRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockScanRepository_List_Call) RunAndReturn(run func(context.Context, repository.ScanFilter) ([]*domain.Scan, int, error)) *MockScanRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, scan
func (_m *MockScanRepository) Update(ctx context.Context, scan *domain.Scan) error {
	ret := _m.Called(ctx, scan)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Scan) error); ok {
		r0 = rf(ctx, scan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScanRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockScanRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - scan *domain.Scan
func (_e *MockScanRepository_Expecter) Update(ctx interface{}, scan interface{}) *MockScanRepository_Update_Call {
	return &MockScanRepository_Update_Call{Call: _e.mock.On("Update", ctx, scan)}
}

func (_c *MockScanRepository_Update_Call) Run(run func(ctx context.Context, scan *domain.Scan)) *MockScanRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Scan))
	})
	return _c
}

func (_c *MockScanRepository_Update_Call) Return(_a0 error) *MockScanRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Scan) error) *MockScanRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, tenantID, id, status
func (_m *MockScanRepository) UpdateStatus(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, status domain.ScanStatus) error {
	ret := _m.Called(ctx, tenantID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.ScanStatus) error); ok {
		r0 = rf(ctx, tenantID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScanRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockScanRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
//   - status domain.ScanStatus
func (_e *MockScanRepository_Expecter) UpdateStatus(ctx interface{}, tenantID interface{}, id interface{}, status interface{}) *MockScanRepository_UpdateStatus_Call {
	return &MockScanRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, tenantID, id, status)}
}

func (_c *MockScanRepository_UpdateStatus_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID, status domain.ScanStatus)) *MockScanRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(domain.ScanStatus))
	})
	return _c
}

func (_c *MockScanRepository_UpdateStatus_Call) Return(_a0 error) *MockScanRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScanRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, domain.ScanStatus) error) *MockScanRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScanRepository creates a new instance of MockScanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanRepository {
	mock := &MockScanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
