package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopy implementations for all CRD types.
// In production, these are generated by controller-gen.

// --- SecurityAgent ---

func (in *SecurityAgent) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(SecurityAgent)
	in.DeepCopyInto(out)
	return out
}

func (in *SecurityAgent) DeepCopyInto(out *SecurityAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SecurityAgentSpec) DeepCopyInto(out *SecurityAgentSpec) {
	*out = *in
	if in.EnabledProbes != nil {
		out.EnabledProbes = make([]string, len(in.EnabledProbes))
		copy(out.EnabledProbes, in.EnabledProbes)
	}
	if in.IgnoredPaths != nil {
		out.IgnoredPaths = make([]string, len(in.IgnoredPaths))
		copy(out.IgnoredPaths, in.IgnoredPaths)
	}
	if in.IgnoredProcesses != nil {
		out.IgnoredProcesses = make([]string, len(in.IgnoredProcesses))
		copy(out.IgnoredProcesses, in.IgnoredProcesses)
	}
}

func (in *SecurityAgentStatus) DeepCopyInto(out *SecurityAgentStatus) {
	*out = *in
	if in.LastHeartbeat != nil {
		out.LastHeartbeat = in.LastHeartbeat.DeepCopy()
	}
}

func (in *SecurityAgentList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(SecurityAgentList)
	in.DeepCopyInto(out)
	return out
}

func (in *SecurityAgentList) DeepCopyInto(out *SecurityAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]SecurityAgent, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// --- SecurityPolicy ---

func (in *SecurityPolicy) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *SecurityPolicy) DeepCopyInto(out *SecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *SecurityPolicySpec) DeepCopyInto(out *SecurityPolicySpec) {
	*out = *in
	if in.ScanTypes != nil {
		out.ScanTypes = make([]string, len(in.ScanTypes))
		copy(out.ScanTypes, in.ScanTypes)
	}
	if in.SLAOverrides != nil {
		out.SLAOverrides = new(SLAOverrides)
		*out.SLAOverrides = *in.SLAOverrides
	}
	if in.ExcludedPaths != nil {
		out.ExcludedPaths = make([]string, len(in.ExcludedPaths))
		copy(out.ExcludedPaths, in.ExcludedPaths)
	}
	if in.NamespaceSelector != nil {
		out.NamespaceSelector = in.NamespaceSelector.DeepCopy()
	}
}

func (in *SecurityPolicyList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *SecurityPolicyList) DeepCopyInto(out *SecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]SecurityPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// --- MonitoringConfig ---

func (in *MonitoringConfig) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *MonitoringConfigSpec) DeepCopyInto(out *MonitoringConfigSpec) {
	*out = *in
	if in.EnabledProbes != nil {
		out.EnabledProbes = make([]string, len(in.EnabledProbes))
		copy(out.EnabledProbes, in.EnabledProbes)
	}
	if in.IgnoredPaths != nil {
		out.IgnoredPaths = make([]string, len(in.IgnoredPaths))
		copy(out.IgnoredPaths, in.IgnoredPaths)
	}
	if in.IgnoredProcesses != nil {
		out.IgnoredProcesses = make([]string, len(in.IgnoredProcesses))
		copy(out.IgnoredProcesses, in.IgnoredProcesses)
	}
	if in.Rules != nil {
		out.Rules = make([]RuntimeRule, len(in.Rules))
		copy(out.Rules, in.Rules)
	}
}

func (in *MonitoringConfigList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitoringConfigList) DeepCopyInto(out *MonitoringConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]MonitoringConfig, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
